// =============================================================================
// NWIS Backend — Shift Handover Service
// =============================================================================
// Generates structured shift handover reports for drilling engineers and
// operations supervisors, aggregating active telemetry, open alerts, recent
// geological/drilling events, active risk predictions, and acknowledgment states.
// =============================================================================

const db = require('../config/database');

const handoverService = {
  /**
   * Generate shift handover report for a well.
   * @param {string} wellId - UUID of well
   * @returns {Promise<object>} handover data payload
   */
  async generateHandoverReport(wellId) {
    const [wellResult, openAlerts, recentEvents, riskPredictions, latestParams] = await Promise.all([
      db.query('SELECT * FROM wells WHERE id = $1', [wellId]),
      db.query(
        `SELECT a.*, u.name AS acknowledged_by_name
         FROM alerts a
         LEFT JOIN users u ON a.acknowledged_by = u.id
         WHERE a.well_id = $1 AND a.status != 'resolved'
         ORDER BY a.generated_at DESC
         LIMIT 20`,
        [wellId]
      ),
      db.query(
        `SELECT de.*, f.name AS formation_name
         FROM drilling_events de
         LEFT JOIN formations f ON de.formation_id = f.id
         WHERE de.well_id = $1
         ORDER BY de.created_at DESC
         LIMIT 10`,
        [wellId]
      ),
      db.query(
        `SELECT * FROM risk_predictions
         WHERE well_id = $1
         ORDER BY created_at DESC
         LIMIT 10`,
        [wellId]
      ),
      db.query(
        `SELECT * FROM drilling_parameters
         WHERE well_id = $1
         ORDER BY timestamp DESC
         LIMIT 1`,
        [wellId]
      ),
    ]);

    const well = wellResult.rows[0];
    if (!well) {
      const err = new Error('Well not found');
      err.status = 404;
      throw err;
    }

    const now = new Date();

    return {
      report_type: 'SHIFT_HANDOVER',
      generated_at: now.toISOString(),
      shift_date: now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
      shift_time: now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
      well: {
        id: well.id,
        well_name: well.well_name,
        field: well.field,
        status: well.status,
        current_depth_m: well.current_depth,
        total_depth_m: well.total_depth,
        operator: well.operator || 'Oil India Limited / ONGC',
      },
      current_parameters: latestParams.rows[0]
        ? {
            depth: parseFloat(latestParams.rows[0].depth),
            wob: parseFloat(latestParams.rows[0].wob),
            rpm: parseFloat(latestParams.rows[0].rpm),
            torque: parseFloat(latestParams.rows[0].torque),
            rop: parseFloat(latestParams.rows[0].rop),
            mud_weight: parseFloat(latestParams.rows[0].mud_weight),
            standpipe_pressure: parseFloat(latestParams.rows[0].standpipe_pressure),
            hook_load: parseFloat(latestParams.rows[0].hook_load),
            flow_out_pct: latestParams.rows[0].additional_parameters?.flow_out_pct ?? null,
            pit_volume_m3: latestParams.rows[0].additional_parameters?.pit_volume_m3 ?? null,
            total_gas_pct: latestParams.rows[0].additional_parameters?.total_gas_pct ?? null,
            timestamp: latestParams.rows[0].timestamp,
          }
        : null,
      open_alerts: openAlerts.rows.map((a) => ({
        id: a.id,
        risk_type: a.risk_type,
        severity: a.severity,
        message: a.message,
        status: a.status,
        score: a.score !== null ? parseFloat(a.score) : null,
        first_seen_depth: a.first_seen_depth,
        last_seen_depth: a.last_seen_depth,
        occurrence_count: a.occurrence_count || 1,
        generated_at: a.generated_at,
        acknowledged_by: a.acknowledged_by_name || null,
        acknowledged_at: a.acknowledged_at,
        feedback: a.feedback || null,
      })),
      recent_events: recentEvents.rows.map((e) => ({
        id: e.id,
        event_type: e.event_type,
        severity: e.severity,
        depth: parseFloat(e.depth),
        formation: e.formation_name,
        description: e.description,
        created_at: e.created_at,
      })),
      active_risks: riskPredictions.rows.map((r) => ({
        id: r.id,
        risk_type: r.risk_type,
        score: parseFloat(r.score),
        risk_level: r.risk_level,
        depth: parseFloat(r.depth),
        explanation: r.explanation,
      })),
      disclaimer:
        'This handover report is auto-generated by eRTMAC-NWIS. It is for informational purposes only and does not replace a certified drilling programme or direct engineer-to-engineer verbal handover.',
    };
  },
};

module.exports = handoverService;
